"""baseline schema

Revision ID: ee6d8799762e
Revises: 
Create Date: 2026-07-05 18:09:04.858490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6d8799762e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='adminrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_profile_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bundle', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_profile_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_profile_bundles_name'), ['name'], unique=True)

    op.create_table('installs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.String(), nullable=False),
    sa.Column('user_upn', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('bearer_token_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installs_install_id'), ['install_id'], unique=True)

    op.create_table('noncompliant_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='devicestatus', native_enum=False), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('mode_prompt', sa.Enum('block', 'confirm', 'audit', name='mode', native_enum=False), nullable=False),
    sa.Column('mode_file', sa.Enum('block', 'confirm', 'audit', name='mode', native_enum=False), nullable=False),
    sa.Column('sites', sa.JSON(), nullable=False),
    sa.Column('grade_profile', sa.String(), nullable=False),
    sa.Column('mip_label_map', sa.JSON(), nullable=False),
    sa.Column('file_check', sa.JSON(), nullable=True),
    sa.Column('user_message', sa.JSON(), nullable=False),
    sa.Column('heartbeat_min', sa.Integer(), nullable=False),
    sa.Column('log_masking', sa.Boolean(), nullable=False),
    sa.Column('classifier', sa.JSON(), nullable=True),
    sa.Column('server_base_url', sa.String(), nullable=True),
    sa.Column('account_collection', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_policy_version'), ['policy_version'], unique=False)

    op.create_table('guard_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('prompt_block', 'prompt_confirm_sent', 'prompt_anonymized_sent', 'file_block', 'file_confirm', 'prompt_allowed', 'file_allowed', 'heartbeat', name='eventtype', native_enum=False), nullable=False),
    sa.Column('install_id', sa.String(), nullable=False),
    sa.Column('user_upn', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('detections', sa.JSON(), nullable=True),
    sa.Column('file', sa.JSON(), nullable=True),
    sa.Column('action', sa.Enum('blocked', 'user_confirmed', 'allowed', name='eventaction', native_enum=False), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['install_id'], ['installs.install_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guard_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_events_install_id'), ['install_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guard_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_events_install_id'))

    op.drop_table('guard_events')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_policy_version'))
        batch_op.drop_index(batch_op.f('ix_policies_is_current'))

    op.drop_table('policies')
    op.drop_table('noncompliant_devices')
    with op.batch_alter_table('installs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installs_install_id'))

    op.drop_table('installs')
    with op.batch_alter_table('grade_profile_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_profile_bundles_name'))

    op.drop_table('grade_profile_bundles')
    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
